import { TListItem } from '../component/listing/ListingCard';

export const listing: TListItem[] = [
	{
		id: '1',
		label: 'Apartment in Accra',
		country: 'Ghana',
		price: '108',
		rating: '4',
		host: 'Luxurious Studio in heart of cantonement',
		category: 'private rooms',
		imageSrc: '/images/lag1.webp',
		reservation: 'July 10 - 14',
	},
	{
		id: '2',
		label: 'Apartment in Lagos',
		country: 'Nigeria',
		price: '130',
		rating: '4.4',
		host: 'Luxury Waterfront retreat 3br, pool & spacious',
		category: 'private rooms',
		imageSrc: '/images/lag2.webp',
		reservation: 'July 12 - 14',
	},
	{
		id: '3',
		label: 'Apartment in Lagos',
		country: 'Nigeria',
		price: '150',
		rating: '4.8',
		host: '2 bedroom waterfront apartment',
		category: 'private rooms',
		imageSrc: '/images/lag3.webp',
		reservation: 'July 13 - 15',
	},
	{
		id: '4',
		label: 'Apartment in Lagos',
		country: 'Nigeria',
		price: '150',
		rating: '4.8',
		host: '2 bedroom waterfront apartment',
		category: 'private rooms',
		imageSrc: '/images/lag3.webp',
		reservation: 'July 10 - 14',
	},
	{
		id: '5',
		label: 'Apartment in Lagos',
		country: 'Nigeria',
		price: '150',
		rating: '4.8',
		host: '2 bedroom waterfront apartment',
		category: 'private rooms',
		imageSrc: '/images/lag3.webp',
		reservation: 'July 14 - 17',
	},
	{
		id: '6',
		label: 'Apartment in Lagos',
		country: 'Nigeria',
		price: '150',
		rating: '4.8',
		host: '2 bedroom waterfront apartment',
		category: 'private rooms',
		imageSrc: '/images/lag3.webp',
		reservation: 'July 15 - 17',
	},
	{
		id: '7',
		label: 'Apartment in Lagos',
		country: 'Nigeria',
		price: '150',
		rating: '4.8',
		host: '2 bedroom waterfront apartment',
		category: 'private rooms',
		imageSrc: '/images/lag3.webp',
		reservation: 'July 11 - 13',
	},
];
